### PR TITLE
Add initial Omics Integrator 1 and 2 Docker images

### PR DESCRIPTION
**Pull request by agitter**
Both Omics Integrator 1 and 2 have functional preliminary Docker wrappers.  There are Python test scripts demonstrating their usage.  The readmes list several remaining TODOs, but this is a good time to merge because we can work on prepare inputs for these methods and polishing the Docker images in parallel.

### CODE REVIEW

**Comment by ajshedivy** [comment]
I was able to build the docker images locally, but I still have some issues with windows style paths in the test scripts. Are you using git for windows? It still seems that I need some conversion logic in order to mount the volumes correctly

```
if os.name == 'nt':
    input_dir = str(input_dir).replace("\\", "/").replace("C:", "//c")
```

**Comment by agitter** [comment]
Interesting.  Let's try to resolve this before merging.  Could you please copy the full output with the error message you get you when you don't convert the paths?

What version of Git for Windows do you have?  This is mine
```
$ git --version
git version 2.31.0.windows.1
```

**Comment by ajshedivy** [comment]
I updated my git version, but doesn't seem to fix issue. here is error message:
```
Running Omics Integrator 2 with arguments: OmicsIntegrator -e oi2-edges.txt -p o
i2-prizes.txt -o . -g 0
Traceback (most recent call last):
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\api\cli
ent.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\requests\model
s.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url:
https://192.168.99.100:2376/v1.40/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ajshe\OneDrive\Documents\Gitter-Lab\reconstruction\pathway-reco
nstruction-enhancer\docker-wrappers\OmicsIntegrator2\test-oi2.py", line 39, in <
module>
    main()
  File "C:\Users\ajshe\OneDrive\Documents\Gitter-Lab\reconstruction\pathway-reco
nstruction-enhancer\docker-wrappers\OmicsIntegrator2\test-oi2.py", line 27, in m
ain
    out = client.containers.run('agitter/omics-integrator-2',
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\models\
containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\models\
containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\api\con
tainer.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\api\con
tainer.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\api\cli
ent.py", line 274, in _result
    self._raise_for_status(response)
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\api\cli
ent.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Users\ajshe\anaconda3\envs\snakemake\lib\site-packages\docker\errors.
py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for https://192.168.99.100:2376/v1.40/c
ontainers/create: Internal Server Error ("invalid volume specification: 'C:\User
s\ajshe\OneDrive\Documents\Gitter-Lab\reconstruction\pathway-reconstruction-enha
ncer\docker-wrappers\OmicsIntegrator2\..\..\input:/OmicsIntegrator2:rw'")

```

**Comment by agitter** [comment]
We compared environments and found we both have version 4.4.1 of the docker Python package, but Adam has Docker 19.03.1 and I have 20.10.5.  That could possibly explain the different behavior.  Docker 19.03.02 [release notes](https://docs.docker.com/engine/release-notes/19.03/#client-7) include "Fix Windows absolute path detection on non-Windows", which seems relevant.

However, we decided to try to fix this in Adam's environment.  Future users may not have the latest version of Docker, even if that is the root cause.

**Comment by agitter** [comment]
@ajshedivy could you please test the updated `test-oi2.py`?  I'm wondering whether it is necessary to replace the drive letter or if the posix style path is sufficient.

**Comment by agitter** [comment]
I'm going to merge per @ajshedivy's confirmation that the tests pass now on his local machine.

**Pull request merged**
